### ISSUE TITLE
目前在 设置 > 外观 中切换主题是不会重载窗口的，但用插件会重载窗口

### ISSUE THREAD

**Issue by TCOTC** [frostime/sy-theme-change#7]
[Call `window.destroyTheme():Promise<void>` instead of refreshing when switching themes #8178](https://github.com/siyuan-note/siyuan/issues/8178)

**Comment by frostime** [comment]
这个插件实现不了，思源内部在调用 `destroyTheme` 之后还会有别的额外操作才能实现切换主题，插件无法访问到这些操作变量，所以只能简单粗暴地重载。

**Comment by TCOTC** [comment]
@frostime 希望改成用 "/api/ui/reloadUI" 刷新

相关：https://ld246.com/article/1726311206127/comment/1752302685638#comments
